version: '3.8'

services:
  database:
    image: postgres:13-alpine
    container_name: mobility_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobility
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - mobility-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mobility-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - mobility-pgadmin-data:/var/lib/pgadmin

volumes:
  mobility-data:
  mobility-pgadmin-data:
